locals {
  pg_host = local.platform.postgres_host
  pg_port = local.platform.postgres_port

  dsn = {
    for role, db in {
      ingest_writer = postgresql_database.warehouse.name
      dbt_runner    = postgresql_database.warehouse.name
      store_app     = postgresql_database.store.name
      airflow       = postgresql_database.airflow.name
    } : role => "postgresql://${role}:${random_password.role[role].result}@${local.pg_host}:${local.pg_port}/${db}"
  }

  # Environment contract outputs (spec 01 §4.2), host-facing values. Keys that don't apply are empty.
  contract = {
    STREAMING_BACKEND       = "kafka"
    KAFKA_BOOTSTRAP_SERVERS = local.platform.kafka_bootstrap_host
    GCP_PROJECT_ID          = ""
    EVENTS_TOPIC            = kafka_topic.this["events"].name
    EVENTS_DLQ_TOPIC        = kafka_topic.this["events_dlq"].name
    WAREHOUSE_BACKEND       = "postgres"
    WAREHOUSE_DSN           = local.dsn["ingest_writer"]
    WAREHOUSE_DATASET       = ""
    WAREHOUSE_RAW_SCHEMA    = postgresql_schema.raw.name
    STORE_DB_DSN            = local.dsn["store_app"]
    DBT_WAREHOUSE_DSN       = local.dsn["dbt_runner"]
    AIRFLOW_DB_DSN          = local.dsn["airflow"]
  }
}

resource "local_sensitive_file" "env" {
  filename        = "${path.module}/../../../../.env.${var.environment}"
  file_permission = "0600"
  content = join("", concat(
    ["# Generated by terraform/envs/${var.environment}/20-resources. Do not edit; run `make env`.\n"],
    [for k in sort(keys(local.contract)) : "${k}=${local.contract[k]}\n"],
  ))
}

output "contract" {
  description = "Environment contract (spec 01 §4.2), as written to .env.<environment>."
  value       = local.contract
  sensitive   = true
}
